### ISSUE TITLE
论文和代码

### ISSUE THREAD

**Issue by ccq195** [youthHan/HVRNet#1]
作者您好，我从vlase会议中了解到了您这篇论文，想请问一下您这篇论文和代码还有多久会公布呢？非常想学习一下

**Comment by youthHan** [comment]
Sorry for the late reply.
The paper could be found [here](http://www.ecva.net/papers/eccv_2020/papers_ECCV/papers/123660426.pdf), available on ECVA.
The code is under cleaning. Due to my heavy workload, the release is suffering a delay and it will be finished in two months.

**Comment by youthHan** [comment]
@ccq195 The link of the paper has been updated.

**Comment by ccq195** [comment]
thanks you very much.  I've already downloaded it

**Comment by ccq195** [comment]
> @ccq195 The link of the paper has been updated.

thanks you very much. I've already downloaded it

**Comment by zpyi** [comment]
> Sorry for the late reply.
> The paper could be found [here](http://www.ecva.net/papers/eccv_2020/papers_ECCV/papers/123660426.pdf), available on ECVA.
> The code is under cleaning. Due to my heavy workload, the release is suffering a delay and it will be finished in two months.

6 months later...Looking forward to your code

**Comment by zpyi** [comment]
> Sorry for the late reply.
> The paper could be found [here](http://www.ecva.net/papers/eccv_2020/papers_ECCV/papers/123660426.pdf), available on ECVA.
> The code is under cleaning. Due to my heavy workload, the release is suffering a delay and it will be finished in two months.

8 months later... Looking forward to your code, I am still here...

**Comment by yancie-yjr** [comment]
666
