### ISSUE TITLE
question about relation regularization loss in Eq.(6)

### ISSUE THREAD

**Issue by junliang230** [youthHan/HVRNet#3]
As described in the paper, d(αtarget , α+) > d(αtarget  , α-)  + λ. And d is Euclidean distance. However, from my perspective, since αtarget and α+ are belong to the same category,  αtarget and α- are belong to different category. αtarget should be more similar with α+ than α-. So, d(αtarget , α+) should be smaller than d(αtarget  , α-). Could you please tell me what I misunderstood. thanks for your reply.

**Comment by youthHan** [comment]
> As described in the paper, d(αtarget , α+) > d(αtarget , α-) + λ.

Yes, this is indeed the formulation we used in our implementation.

> Could you please tell me what I misunderstood.

Intuitively, the loss would be in the original triplet loss form to make `d(αtarget , α+) < d(αtarget , α-) + λ`. It indeed improved the result. 
Our further consideration is that, with the inter-video relation constructed via triplet selection&inter(1) and detection supervision performed on intra(2)&inter(1) in Fig.3 in the paper, the model could learn the proposal relation among different videos to some extent. 
In the metric loss here, we considered the α- as the context proposals most related to αtarget and α+ as the proposal of a different object in the same category. To have proposals of the certain object clustered closely, we constraint the model with the inversed triplet loss. And the performance got further improvement.
All in all, with the selected proposal triplet, the inter-video relation is constructed and the designed metric loss could further refine the model.

**Comment by junliang230** [comment]
thanks for your reply
